---
channels:
  - "defaults"
  - "conda-forge"
  - "beakerx"

dependencies:
  - jupyterlab >=2.0,<3.0
  - matplotlib
  - pandas >= 1.3
  - protobuf # to fix tensorflow issue
  - scikit-learn
  - seaborn
  - ta-lib
  - tensorflow >= 2.6.2
  # beakerx extensions
  - beakerx_kernel_autotranslation
  - beakerx_tabledisplay
  - beakerx_widgets
  - pip
  - pip:
    - fredapi
    - ipykernel
    - import-ipynb
    - mlflow
